# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#####################################################
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

timezone: Europe/Rome
encoding: utf-8

# source: ./jekyll
# destination: ./blog

title: Stefano Collovati - Personal Website
description: >- # this means to ignore newlines until "baseurl:"
  Learning Technologist
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://stefanocollovati.it" # the base hostname & protocol for your site, e.g. http://example.com

# vedere https://rubydoc.info/gems/minima/
github_username:  scollovati
linkedin_username:  scollovati
rss: rss

permalink: pretty

# specific pages folder
collections:
  pages:
    output: true
    permalink: /:path/


#####################################################
# Serve configurations
livereload: true #for development

#####################################################
# Build configurations
# incremental: BOOL
JEKYLL_ENV: production
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
